language: ruby

notifications:
    slack: rmit-programming-club:4oYYWHQc3D8klHMUIw3ShFS9

env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
before_script:
  - psql -c 'create database my_app_test' -U postgres
bundler_args: --binstubs=./bundler_stubs